version: '3.8'

services:
  backend:
    build: ./back
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  frontend:
    build: ./front
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  node_modules: